let t={},state={},sortKey=null,sortDirection=1;const q=s=>document.querySelector(s);
async function api(path,options={}){const headers={Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})};const response=await fetch(new URL(path,document.baseURI),{...options,headers});let payload;try{payload=await response.json()}catch{throw Error(`Request failed (${response.status}): invalid JSON response`)}if(!response.ok)throw Error(payload.error||`Request failed (${response.status})`);return payload}
function message(text,kind=''){const box=q('#message');box.textContent=text;box.className=kind}
function language(){return (window.hass&&window.hass.language)||document.documentElement.lang||navigator.language||'en'}
function callbackUri(){return new URL('spotify/callback',document.baseURI).href}
async function load(){const lang=language().toLowerCase().startsWith('de')?'de':'en';t=await api('api/i18n/'+lang);t.reset_sorting=t.reset_sorting||(lang==='de'?'Sortierung zurücksetzen':'Reset sorting');state=await api('api/state');document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=t[e.dataset.i18n]);status();form();spotify();tracks();actions();const outcome=new URL(location.href).searchParams.get('spotify');if(outcome==='connected')message(t.spotify_connected);if(outcome==='failed')message(t.spotify_failed,'error')}
function status(){const h=state.jobs.history||{},d=state.jobs.today||{},scheduled=state.schedule.daily_enabled?t.enabled:t.disabled;q('#status').textContent=`${t.spotify}: ${t[state.spotify.state]} · ${t.preview}: ${t[state.preview.state]} · ${t.playlist_preview}: ${state.today.count} · ${t.last_history}: ${h.ended_at||'—'} · ${t.last_today}: ${d.ended_at||'—'} · ${t.scheduler}: ${scheduled} (${state.schedule.daily_time}) · ${t.history_poll_minutes}: ${state.schedule.history_interval_minutes}`}
function form(){const s=state.settings,fields=['today_size','rare_weight','artist_gap','history_poll_minutes','today_schedule_time','target_playlist_name'],numeric={today_size:[1],rare_weight:[0,100],artist_gap:[0],history_poll_minutes:[1]};q('#settings').replaceChildren(...fields.map(key=>{const label=document.createElement('label'),input=document.createElement('input');input.name=key;input.value=s[key];if(numeric[key]){input.type='number';input.min=numeric[key][0];if(numeric[key][1]!==undefined)input.max=numeric[key][1]}else if(key==='today_schedule_time')input.type='time';label.append(t[key]+' ',input);return label}),weight(),check(),button(t.save,'submit','primary'));q('#settings').onsubmit=async e=>{e.preventDefault();try{const d=Object.fromEntries(new FormData(e.target));d.today_schedule_enabled=e.target.today_schedule_enabled.checked;const result=await api('api/settings',{method:'POST',body:JSON.stringify(d)});state=result.state;message(t.saved);status();form();actions()}catch(error){message(error.message,'error')}}}
function weight(){const label=document.createElement('output');label.setAttribute('aria-readonly','true');label.textContent=`${t.long_weight}: ${state.settings.long_weight}%`;return label}function check(){const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.name='today_schedule_enabled';input.checked=state.settings.today_schedule_enabled;label.append(t.today_schedule_enabled,input);return label}function button(label,type='button',variant=''){const b=document.createElement('button');b.type=type;b.textContent=label;if(variant)b.className=variant;return b}
function spotify(){const area=q('#spotify-auth');area.replaceChildren();const notice=document.createElement('p');notice.textContent=state.spotify.available?(t.spotify_connected||'Connected in Home Assistant.'):(t.not_connected||'Connect Spotify in the Home Assistant integration.');area.append(notice)}
function actions(){const area=q('#actions');area.replaceChildren(...['sync','preview','publish','run'].map(action=>{const b=button(t[action]);b.disabled=!state.spotify.available;b.onclick=async()=>{try{state=await api('api/actions/'+action,{method:'POST'});message(t.action_complete);load()}catch(error){message(error.message,'error')}};return b}));if(!state.spotify.available){const reason=document.createElement('p');reason.textContent=t.not_connected;area.append(reason)}}
function relativeDate(value){if(!value)return '—';const date=new Date(value);if(Number.isNaN(date.getTime()))return '—';const seconds=Math.max(0,Math.round((Date.now()-date.getTime())/1000)),de=language().toLowerCase().startsWith('de');if(seconds<60)return de?'gerade eben':'just now';const minutes=Math.floor(seconds/60);if(minutes<60)return de?`vor ${minutes} Min.`:`${minutes} min ago`;const hours=Math.floor(minutes/60);if(hours<24)return de?`vor ${hours} Std.`:`${hours} hr ago`;const days=Math.floor(hours/24);if(days===1)return de?'gestern':'yesterday';if(days<7)return de?`vor ${days} Tagen`:`${days} days ago`;const weeks=Math.floor(days/7);if(weeks<5)return de?`vor ${weeks} Wochen`:`${weeks} weeks ago`;return new Intl.DateTimeFormat(language(),{dateStyle:'medium'}).format(date)}
function localDateTime(value){const date=new Date(value);return Number.isNaN(date.getTime())?'':new Intl.DateTimeFormat(language(),{dateStyle:'medium',timeStyle:'short'}).format(date)}
function compareTracks(a,b,key){const x=a[key],y=b[key];if(key==='last_played')return(Date.parse(x||'')||0)-(Date.parse(y||0)||0);if(typeof x==='number'||typeof y==='number')return Number(x||0)-Number(y||0);return String(x||'').localeCompare(String(y||''),language(),{sensitivity:'base'})}
function tracks(){q('#filter').placeholder=t.filter;const draw=()=>{const filter=q('#filter').value.toLowerCase(),rows=state.today.tracks.map((track,index)=>({track,index})).filter(({track})=>`${track.track_name||''} ${track.artist_name||''}`.toLowerCase().includes(filter));if(sortKey)rows.sort((a,b)=>{const result=compareTracks(a.track,b.track,sortKey);return result?result*sortDirection:a.index-b.index});const body=q('#tracks');body.replaceChildren(...rows.map(({track})=>{const row=document.createElement('tr');['track_name','artist_name','combined_score','play_count','last_played'].forEach(key=>{const cell=document.createElement('td');if(key==='last_played'){cell.textContent=relativeDate(track[key]);cell.title=localDateTime(track[key])}else cell.textContent=key==='combined_score'?Number(track[key]||0).toFixed(1):(track[key]||'—');row.append(cell)});return row}))};q('#filter').oninput=draw;q('#reset-sorting').onclick=()=>{sortKey=null;sortDirection=1;draw()};document.querySelectorAll('[data-sort]').forEach(header=>header.onclick=()=>{const key=header.dataset.sort;sortDirection=sortKey===key?-sortDirection:1;sortKey=key;draw()});draw()}load().catch(error=>message(error.message,'error'));
