let t={},state={},sortKey='combined_score',sortDirection=-1;const q=s=>document.querySelector(s);
async function api(path,options={}){const headers={Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})};const response=await fetch(new URL(path,document.baseURI),{...options,headers});let payload;try{payload=await response.json()}catch{throw Error(`Request failed (${response.status}): invalid JSON response`)}if(!response.ok)throw Error(payload.error||`Request failed (${response.status})`);return payload}
function message(text,kind=''){const box=q('#message');box.textContent=text;box.className=kind}
function language(){return (window.hass&&window.hass.language)||document.documentElement.lang||navigator.language||'en'}
function callbackUri(){return new URL('spotify/callback',document.baseURI).href}
async function load(){const lang=language().toLowerCase().startsWith('de')?'de':'en';t=await api('api/i18n/'+lang);state=await api('api/state');document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=t[e.dataset.i18n]);status();form();spotify();tracks();actions();const outcome=new URL(location.href).searchParams.get('spotify');if(outcome==='connected')message(t.spotify_connected);if(outcome==='failed')message(t.spotify_failed,'error')}
function status(){const h=state.jobs.history||{},d=state.jobs.today||{};q('#status').textContent=`${t.spotify}: ${t[state.spotify.state]} · ${t.preview}: ${t[state.preview.state]} · ${t.today}: ${state.today.count} · ${t.last_history}: ${h.ended_at||'—'} · ${t.last_today}: ${d.ended_at||'—'} · ${t.history_poll_minutes}: ${state.schedule.history_interval_minutes} · ${t.today_schedule_time}: ${state.schedule.daily_time}`}
function form(){const s=state.settings,fields=['today_size','rare_weight','artist_gap','history_poll_minutes','today_schedule_time','target_playlist_name'];q('#settings').replaceChildren(...fields.map(key=>{const label=document.createElement('label'),input=document.createElement('input');input.name=key;input.value=s[key];label.append(t[key]+' ',input);return label}),weight(),check(),button(t.save,'submit','primary'));q('#settings').onsubmit=async e=>{e.preventDefault();try{const d=Object.fromEntries(new FormData(e.target));d.today_schedule_enabled=e.target.today_schedule_enabled.checked;const result=await api('api/settings',{method:'POST',body:JSON.stringify(d)});state=result.state;message(t.saved);status();form();actions()}catch(error){message(error.message,'error')}}}
function weight(){const label=document.createElement('output');label.textContent=`${t.long_weight}: ${state.settings.long_weight}%`;return label}function check(){const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.name='today_schedule_enabled';input.checked=state.settings.today_schedule_enabled;label.append(t.today_schedule_enabled,input);return label}function button(label,type='button',variant=''){const b=document.createElement('button');b.type=type;b.textContent=label;if(variant)b.className=variant;return b}
function spotify(){const area=q('#spotify-auth');area.replaceChildren();if(state.spotify.available)return;const notice=document.createElement('p');notice.textContent=t.save_does_not_connect;const uri=document.createElement('code');uri.textContent=callbackUri();const help=document.createElement('p');help.textContent=t.redirect_uri;help.append(' ',uri);const connect=button(t.connect_spotify,'button','primary');connect.onclick=async()=>{try{message(t.authorization_starting,'notice');const result=await api('api/spotify/authorize',{method:'POST',body:JSON.stringify({callback_uri:callbackUri()})});location.assign(result.authorization_url)}catch(error){message(error.message,'error')}};area.append(notice,connect,help)}
function actions(){const area=q('#actions');area.replaceChildren(...['sync','preview','publish','run'].map(action=>{const b=button(t[action]);b.disabled=!state.spotify.available;b.onclick=async()=>{try{state=await api('api/actions/'+action,{method:'POST'});message(t.action_complete);load()}catch(error){message(error.message,'error')}};return b}));if(!state.spotify.available){const reason=document.createElement('p');reason.textContent=t.not_connected;area.append(reason)}}
function tracks(){q('#filter').placeholder=t.filter;const draw=()=>{const filter=q('#filter').value.toLowerCase();const rows=state.today.tracks.filter(track=>`${track.track_name||''} ${track.artist_name||''}`.toLowerCase().includes(filter)).sort((a,b)=>{const x=a[sortKey]||'',y=b[sortKey]||'';return x>y?sortDirection:x<y?-sortDirection:0});const body=q('#tracks');body.replaceChildren(...rows.map(track=>{const row=document.createElement('tr');['track_name','artist_name','combined_score','play_count','last_played'].forEach(key=>{const cell=document.createElement('td');cell.textContent=key==='combined_score'?Number(track[key]||0).toFixed(1):(track[key]||'—');row.append(cell)});return row}))};q('#filter').oninput=draw;document.querySelectorAll('[data-sort]').forEach(header=>header.onclick=()=>{const key=header.dataset.sort;sortDirection=sortKey===key?-sortDirection:-1;sortKey=key;draw()});draw()}load().catch(error=>message(error.message,'error'));
