import json
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import MagicMock, patch

from application_paths import ApplicationPaths
from client import SpotifyClient
import publish


class FakeSpotifyClient:
    def __init__(self, target_playlist):
        self.target_playlist = target_playlist
        self.calls = []
        self.request_count = 0

    def find_owned_playlist_by_name(self, name):
        self.calls.append(("find", name))
        return self.target_playlist

    def create_private_playlist(self, name):
        self.calls.append(("create_private", name))
        return {"id": "created-target"}

    def set_playlist_private(self, playlist_id):
        self.calls.append(("set_private", playlist_id))

    def rename_playlist(self, playlist_id, name):
        self.calls.append(("rename", playlist_id, name))

    def replace_playlist_items(self, playlist_id, uris):
        self.calls.append(("replace", playlist_id, uris))


class PublishPrivacyTests(unittest.TestCase):
    def setUp(self):
        self.directory = tempfile.TemporaryDirectory()
        self.paths = ApplicationPaths.from_data_dir(self.directory.name)
        self.paths.ensure_runtime_directories()
        self.paths.today_tracks_path.write_text(
            json.dumps(
                {
                    "input_fingerprint": "current-fingerprint",
                    "tracks": [
                        {
                            "position": 1,
                            "track_uri": "spotify:track:one",
                            "artist_name": "Artist",
                            "track_name": "Track",
                        }
                    ],
                }
            ),
            encoding="utf-8",
        )

    def tearDown(self):
        self.directory.cleanup()

    def run_publish(self, client, *arguments):
        with (
            patch.object(sys, "argv", ["publish.py", *arguments]),
            patch("publish.application_paths_from_args", return_value=self.paths),
            patch("publish.validate_scoring_freshness", return_value="current-fingerprint"),
            patch("publish.SpotifyClient", return_value=client),
        ):
            publish.main()

    def test_real_publish_creates_a_private_target_once_when_missing(self):
        client = FakeSpotifyClient(target_playlist=None)

        self.run_publish(client, "--write")

        self.assertEqual(
            client.calls,
            [
                ("find", "Today"),
                ("create_private", "Today"),
                ("rename", "created-target", "Today"),
                ("set_private", "created-target"),
                ("replace", "created-target", ["spotify:track:one"]),
            ],
        )

    def test_client_creates_target_with_private_non_collaborative_flags(self):
        client = SpotifyClient.__new__(SpotifyClient)
        client._sp = MagicMock()
        client._sp.current_user.return_value = {"id": "user-id"}
        client._call = lambda _operation, function, *args, **kwargs: function(
            *args, **kwargs
        )

        client.create_private_playlist("Today")

        client._sp.user_playlist_create.assert_called_once_with(
            "user-id",
            "Today",
            public=False,
            collaborative=False,
            description="Generated by Playlist Assistant",
        )

    def test_real_publish_corrects_persisted_existing_target_before_replacing_tracks(self):
        client = FakeSpotifyClient(target_playlist={"id": "persisted-target", "public": True})

        self.run_publish(client, "--write")

        self.assertEqual(
            client.calls,
            [
                ("find", "Today"),
                ("rename", "persisted-target", "Today"),
                ("set_private", "persisted-target"),
                ("replace", "persisted-target", ["spotify:track:one"]),
            ],
        )

    def test_dry_run_does_not_change_existing_playlist_visibility_or_tracks(self):
        client = FakeSpotifyClient(target_playlist={"id": "persisted-target", "public": True})

        self.run_publish(client)

        self.assertEqual(client.calls, [("find", "Today")])
