import json
import os
import unittest
from io import BytesIO
from pathlib import Path
from urllib.error import HTTPError
from unittest.mock import patch

from ha_app.client import SpotifyApiError, SpotifyClient, SpotifyRateLimited


class _Response:
    def __init__(self, body): self.body = body
    def __enter__(self): return self
    def __exit__(self, *_): return False
    def read(self): return json.dumps(self.body).encode()


class ProxyClientTests(unittest.TestCase):
    def setUp(self):
        self.env = {"PLAYLIST_ASSISTANT_SPOTIFY_PROXY": "http://supervisor/core/api/playlist_assistant/spotify", "SUPERVISOR_TOKEN": "supervisor"}

    def test_operations_are_mapped_without_spotify_credentials(self):
        requests = []
        def open_request(request, timeout):
            requests.append(json.loads(request.data)); return _Response({"id": "user"})
        with patch.dict(os.environ, self.env, clear=True), patch("ha_app.client.urllib.request.urlopen", open_request):
            client = SpotifyClient()
            client.get_recently_played_since(None)
            client.get_all_user_playlists()
            client.get_playlist("playlist")
            client.get_playlist_items("playlist")
            client.create_private_playlist("Today")
            client.prepare_private_playlist("playlist", "Today")
            client.replace_playlist_items("playlist", ["spotify:track:1"])
        self.assertEqual([item["operation"] for item in requests], ["recently_played", "user_playlists", "playlist", "playlist_items", "create_playlist", "playlist_details", "replace_items"])
        self.assertEqual(requests[4], {
            "operation": "create_playlist",
            "path": {},
            "params": None,
            "json": {
                "name": "Today",
                "public": False,
                "collaborative": False,
                "description": "Generated by Playlist Assistant",
            },
        })
        self.assertEqual(requests[5], {
            "operation": "playlist_details",
            "path": {"playlist_id": "playlist"},
            "params": None,
            "json": {"name": "Today", "public": False},
        })
        self.assertEqual(requests[2], {
            "operation": "playlist",
            "path": {"playlist_id": "playlist"},
            "params": None,
            "json": None,
        })
        self.assertEqual(requests[3], {
            "operation": "playlist_items",
            "path": {"playlist_id": "playlist"},
            "params": {"limit": 50, "offset": 0},
            "json": None,
        })
        self.assertNotIn("access_token", json.dumps(requests))

    def test_playlist_items_follow_spotify_pagination_parameters(self):
        requests = []
        responses = iter((
            _Response({"items": [{"item": {"uri": "spotify:track:1"}}], "next": "https://api.spotify.com/v1/playlists/playlist/items?limit=50&offset=50"}),
            _Response({"items": [{"item": {"uri": "spotify:track:2"}}], "next": None}),
        ))
        def open_request(request, timeout):
            requests.append(json.loads(request.data))
            return next(responses)

        with patch.dict(os.environ, self.env, clear=True), patch("ha_app.client.urllib.request.urlopen", open_request):
            items = SpotifyClient().get_playlist_items("playlist")

        self.assertEqual(len(items), 2)
        self.assertEqual(requests[1]["operation"], "playlist_items")
        self.assertEqual(requests[1]["path"], {"playlist_id": "playlist"})
        self.assertEqual(requests[1]["params"], {"limit": "50", "offset": "50"})

    def test_proxy_routes_all_playlist_item_operations_to_current_items_endpoint(self):
        api = Path("custom_components/playlist_assistant/api.py").read_text(encoding="utf-8")

        self.assertIn('"playlist_items": ("GET", "/playlists/{playlist_id}/items")', api)
        self.assertIn('"replace_items": ("PUT", "/playlists/{playlist_id}/items")', api)
        self.assertIn('"append_items": ("POST", "/playlists/{playlist_id}/items")', api)
        self.assertNotIn('/playlists/{playlist_id}/tracks', api)

    def test_proxy_routes_publish_operations_to_february_2026_endpoints(self):
        api = Path("custom_components/playlist_assistant/api.py").read_text(encoding="utf-8")

        self.assertIn('"create_playlist": ("POST", "/me/playlists")', api)
        self.assertIn('"playlist": ("GET", "/playlists/{playlist_id}")', api)
        self.assertIn('"playlist_details": ("PUT", "/playlists/{playlist_id}")', api)
        self.assertNotIn('/users/{user_id}/playlists', api)
        self.assertNotIn('/playlists/{playlist_id}/details', api)

    def test_two_hundred_tracks_use_two_ordered_batches_of_at_most_one_hundred(self):
        requests = []
        uris = [f"spotify:track:{index}" for index in range(200)]

        def open_request(request, timeout):
            requests.append(json.loads(request.data))
            return _Response({"snapshot_id": "snapshot"})

        with patch.dict(os.environ, self.env, clear=True), patch("ha_app.client.urllib.request.urlopen", open_request):
            SpotifyClient().replace_playlist_items("playlist", uris)

        self.assertEqual([request["operation"] for request in requests], ["replace_items", "append_items"])
        self.assertEqual([request["json"]["uris"] for request in requests], [uris[:100], uris[100:]])

    def test_existing_playlist_with_two_hundred_tracks_uses_minimal_details_and_two_writes(self):
        requests = []
        uris = [f"spotify:track:{index}" for index in range(200)]

        def open_request(request, timeout):
            requests.append(json.loads(request.data))
            return _Response({"snapshot_id": "snapshot"})

        with patch.dict(os.environ, self.env, clear=True), patch("ha_app.client.urllib.request.urlopen", open_request):
            client = SpotifyClient()
            client.prepare_private_playlist("playlist", "Today")
            client.replace_playlist_items("playlist", uris)

        self.assertEqual([request["operation"] for request in requests], ["playlist_details", "replace_items", "append_items"])
        self.assertEqual(requests[0]["json"], {"name": "Today", "public": False})
        self.assertNotIn("collaborative", requests[0]["json"])
        self.assertEqual([request["json"]["uris"] for request in requests[1:]], [uris[:100], uris[100:]])

    def test_playlist_item_proxy_failure_logs_safe_status_and_spotify_detail(self):
        error = HTTPError(
            self.env["PLAYLIST_ASSISTANT_SPOTIFY_PROXY"],
            403,
            "Forbidden",
            None,
            BytesIO(b'{"error":"Insufficient client scope"}'),
        )
        with patch.dict(os.environ, self.env, clear=True), \
                patch("ha_app.client.urllib.request.urlopen", side_effect=error), \
                self.assertLogs("playlist_assistant.spotify", "ERROR") as logs:
            client = SpotifyClient()
            with self.assertRaisesRegex(SpotifyApiError, "HTTP 403.*Insufficient client scope") as caught:
                client.get_playlist_items("playlist")

        self.assertEqual(caught.exception.operation, "playlist_items")
        self.assertEqual(caught.exception.http_status, 403)
        self.assertIn("operation=playlist_items status=403 detail=Insufficient client scope", logs.output[0])
        self.assertNotIn(self.env["SUPERVISOR_TOKEN"], "\n".join(logs.output))

    def test_proxy_429_preserves_retry_after_and_quota_reason(self):
        error = HTTPError(
            self.env["PLAYLIST_ASSISTANT_SPOTIFY_PROXY"], 429, "Too Many Requests",
            {"Retry-After": "120"}, BytesIO(b'{"error":"quota exhausted","reason":"QUOTA_EXCEEDED"}'),
        )
        with patch.dict(os.environ, self.env, clear=True), patch("ha_app.client.urllib.request.urlopen", side_effect=error):
            with self.assertRaises(SpotifyRateLimited) as caught:
                SpotifyClient().get_all_user_playlists()

        self.assertEqual(caught.exception.retry_after, 120)
        self.assertEqual(caught.exception.reason, "QUOTA_EXCEEDED")
        self.assertEqual(caught.exception.operation, "current_user_playlists")
